export const FETCH_RESTAURANT_LOADING = "FETCH_RESTAURANT_LOADING";
export const FETCH_RESTAURANT_SUCCESS = "FETCH_RESTAURANT_SUCCESS";
export const FETCH_RESTAURANT_FAIL = "FETCH_RESTAURANT_FAIL";
export const FETCH_RESTAURANTS_LIST_LOADING = "FETCH_RESTAURANTS_LIST_LOADING";
export const FETCH_RESTAURANTS_LIST_SUCCESS = "FETCH_RESTAURANTS_LIST_SUCCESS";
export const FETCH_RESTAURANTS_LIST_FAIL = "FETCH_RESTAURANTS_LIST_FAIL";
export const FILTER_RESTAURANTS_LIST_BY_PRICE_LEVEL =
  "FILTER_RESTAURANTS_LIST_BY_PRICE_LEVEL";
export const SORT_RESTAURANTS_LIST_BY_RATING =
  "SORT_RESTAURANTS_LIST_BY_RATING";
export const ADD_TO_FAVORITES_LIST = "ADD_TO_FAVORITES_LIST";
export const REMOVE_FROM_FAVORITES_LIST = "REMOVE_FROM_FAVORITES_LIST";
